version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: payment_broker
    ports:
      - "5672:5672" 
      - "15672:15672" 
    networks:
      - backend_net

#fastAPI service
  api:
    build:
      context: ./
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - backend_net
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}


networks:
  backend_net:
    driver: bridge